### ISSUE TITLE
Add workflow to update third party notices

### ISSUE THREAD

**Issue by jsumners-nr** [newrelic/newrelic-node-versions#3]
There isn't a common tool for managing Go projects like there is for managing Node.js projects. Thus, there isn't a consistent method to enforce pre-commit hooks for every developer (since `.git/config` is unique to each clone). Therefore, we need to create a GitHub Actions workflow to:

1. Detect when changes are made to the `go.mod` file
2. Parse the `go.mod` file and update the third party notices files (easiest to just regenerate the notice files each time)
3. Open a PR with the changes

**Comment by bizob2828** [comment]
I wouldn't try to automate this. I would just follow the copy that the go agent is using [here](https://github.com/newrelic/go-agent/blob/master/THIRD_PARTY_NOTICES.md)
